apiVersion: apps/v1
kind: Deployment
metadata:
  name: bala-flower-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bala
  template:
    metadata:
      labels: 
        app: bala
    spec:
      containers:
      - name: cart-app
        image: muralisocial123/flower-app:1.0
        resources:
          limits:
            memory: "250Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 3015
--- 
# writing service.yml to expose the applications
apiVersion: v1
kind: Service
metadata:
  name: bala-flower-app-svc
spec:
  selector:
    app: bala
  ports:
  - port: 3016  
    targetPort: 3015
  type: LoadBalancer



